name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0-15.0.pre.16'
          channel: 'master'

      - name: Authenticating Github Action for Google
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: gcloud info
        run: gcloud info

      - name: Enable Flutter Web
        run: flutter config --

      - name: Install dependencies
        run: flutter pub get

      - name: Build the web
        run: flutter build web
      
      - name: Disable gcloud prompts
        run: gcloud config set disable_prompts true

      - name: SCP to server
        run: 'gcloud compute scp --recurse build/web/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_VM_NAME }}:~/.nf/flutter-scp'

      - name: SSH to server
        run: gcloud compute ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_VM_NAME }} --quiet

      - name: Replace flutter folder with latest builder
        run: |
          cd ~/.nf/
          ls
          rm -rf flutter
          mv flutter-scp/ flutter/
          sudo systemctl restart nginx
      # - name: Install
      # - name: Print pwd
      #   run: pwd

      # - name: Deploy to server via ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
