name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0-15.0.pre.16'
          channel: 'master'

      - name: Authenticating Github Action for Google
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: gcloud info
        run: gcloud info

      - name: Enable Flutter Web
        run: flutter config --

      - name: Install dependencies
        run: flutter pub get

      - name: Build the web
        run: flutter build web
      
      - name: Disable gcloud prompts
        run: gcloud config set disable_prompts true

      - name: SCP to server
        run: 'gcloud compute scp --recurse build/web/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_VM_NAME }}:~/.nf/flutter-scp --project=${{ secrets.GCP_PROJECT }} --zone=${{ secrets.GCP_ZONE }}'

      - name: Execute the script on remote via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/.nf/
            rm -rf flutter/
            cp flutter-scp/ flutter-scp-check/
            mv flutter-scp/ flutter/
            sudo systemctl restart nginx
            
